services:
  config-server:
    build:
      pulse-monitoring-config-server
    mem_limit: 200m
    mem_reservation: 50m


  redis:
    image: redis

  pulse-analyser:
    build:
      pulse-analyser
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      -KAFKA_PASSWORD=g_DPMktGTOp52rZNc578fRNkU7GD-Kpc
      -SPRING_PROFILES_ACTIVE=docker
      -REDIS_HOST=redis

  average-populator:
    build:
      pulse-monitoring-average-populator
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      -KAFKA_PASSWORD=g_DPMktGTOp52rZNc578fRNkU7GD-Kpc
      -SPRING_PROFILES_ACTIVE=docker
      -MONGO_PASSWORD=rootroot

  average-reducer:
    build:
      pulse-monitoring-avg-reducer
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      -KAFKA_PASSWORD=g_DPMktGTOp52rZNc578fRNkU7GD-Kpc
      -SPRING_PROFILES_ACTIVE=docker
      -REDIS_HOST=redis

  doctor-patient-data-provider:
    build:
      pulse-monitoring-doctor-data-provider
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      -POSTGRES_PASSWORD=8e886bdac794c0d7a21cadd04c94a7cb56e94af7bf2f81f1e548763fe7c11c39
      -SPRING_PROFILES_ACTIVE=docker

  jumps-notifier:
    build:
      pulse-monitoring-jumps-notifier
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      -KAFKA_PASSWORD=g_DPMktGTOp52rZNc578fRNkU7GD-Kpc
      -SPRING_PROFILES_ACTIVE=docker
      -DATA_PROVIDER_URL=http://doctor-patient-data-provider:8080
      -MAIL_PASSWORD=byoygkvqfuwhfxii
      -USER_NAME=sarvarovtimur@gmail
      -MONGO_PASSWORD=rootroot
  pulse-monitoring-gateway:
    build:
      pulse-monitoring-gateway
    mem_limit: 200m
      mem_reservation: 50m
      environment:
        -SENSORS_HOST=back-office-sensors
        -VISITS_HOST=back-office-visits

  jumps-populator:
    build:
      pulse-monitoring-jumps-populator
    mem_limit: 200m
    mem_reservation: 50m
    environment:
      -KAFKA_PASSWORD=g_DPMktGTOp52rZNc578fRNkU7GD-Kpc
      -SPRING_PROFILES_ACTIVE=docker
      -MONGO_PASSWORD=rootroot

  back-office-visits:
    build:
      pulse-monitoring-visits-back-office
      mem_limit: 200m
      mem_reservation: 50m
      environment:
        -POSTGRES_PASSWORD=8e886bdac794c0d7a21cadd04c94a7cb56e94af7bf2f81f1e548763fe7c11c39

  back-office-sensors:
    build:
      pulse-monitoring-sensor-values-back-office
      mem_limit: 200m
      mem_reservation: 50m
      environment:
        -MONGO_PASSWORD=rootroot
